#goal definition
orunav2_msgs/PathPoint pose
string behavior_tree
---
#result definition
std_msgs/Empty result
---
#feedback definition
orunav2_msgs/PathPoint current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
