weather_detector:
  ros__parameters:
    rate: 10
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    image_topic: "<robot_namespace>/intel_realsense_r200_depth/image_raw"
    service_name: "<robot_namespace>/get_weather_condition"
    image:
        type: "image"
        topic: "<robot_namespace>/intel_realsense_r200_depth/image_raw"
