costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 4
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/area_filter_mask"
    base: 100.0
    multiplier: -1.0
filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/area_filter_mask"
    yaml_filename: "area_mask.yaml"
