coordinator:
 ros__parameters:
    robot1/footprint/rear_left_y: 0.3
    robot1/footprint/rear_left_x: -0.2 
    robot1/footprint/rear_right_y: -0.3 
    robot1/footprint/front_left_x: 1.9 
    robot1/footprint/front_left_y: 0.3
    robot1/footprint/front_right_x: 1.9 
    robot1/footprint/front_right_y: -0.3
    robot1/calibration/curve_width_in_odom_frame: 5.0 
    robot1/calibration/curve_height_in_odom_frame: 3.0
    
    
